### ISSUE TITLE
Any example with PDB?

### ISSUE THREAD

**Issue by ghost** [PeptoneLtd/nerfax#1]
Hi, is there any example how to use nerfax with PDB files? Basically, how to use nerfax to convert 3D coordinates to internal coordinates and use internal coordinates to reconstruct 3D coordinates? Thanks!

**Comment by oliverdutton** [comment]
That is indeed missing, thanks. Added an example downloads a pdb model from AF2DB then converts forward and back to internal coordinates. 
[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/PeptoneLtd/nerfax/blob/main/notebooks/Example_reconstruction_from_pdb.ipynb)

Hope that helps,
Oliver
